#!/usr/bin/env python3
"""Write LaTeX metrics and tables for paper v2 (Arc A)."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, List


def _fmt(x: float) -> str:
    return f"{x:.3f}"


def _fmt_pm(mean: float, std: float) -> str:
    return f"{_fmt(mean)} $\\pm$ {_fmt(std)}"


def _mean_std(vals: List[float]) -> tuple[float, float]:
    nums = [float(v) for v in vals]
    if not nums:
        return 0.0, 0.0
    m = sum(nums) / len(nums)
    var = sum((v - m) ** 2 for v in nums) / len(nums)
    return m, var ** 0.5


def _ms(payload: Dict[str, Any], metric: str, prefix: str = "") -> Dict[str, float | int]:
    key = f"{prefix}{metric}" if prefix else metric
    return payload.get(key, payload.get(metric, {"mean": 0.0, "std": 0.0, "n": 0}))


def write_metrics_v2(metrics: Dict[str, Any], out: Path, corrected: Dict[str, Any] | None) -> None:
    models = metrics.get("models", {})
    nanda = models.get("nanda_a_mlp", {})
    minimal = models.get("trm_minimal", {})
    corr_nanda = (corrected or {}).get("nanda_a_mlp", nanda.get("corrected_fve", {}))
    corr_min = (corrected or {}).get("trm_minimal", minimal.get("corrected_fve", {}))

    nanda_fve = float(corr_nanda.get("mean_fve_adaptive", _ms(nanda, "logit_trig_fve_adaptive", "final_").get("mean", 0.0)))
    minimal_fve = float(corr_min.get("mean_fve_adaptive", _ms(minimal, "logit_trig_fve_adaptive", "final_").get("mean", 0.0)))
    nanda_clean = int(corr_nanda.get("n_seeds_adaptive_ge_0.95", 0))
    minimal_clean = int(corr_min.get("n_seeds_adaptive_ge_0.95", 0))

    mainline = minimal.get("mainline_seed_run", minimal.get("best_seed_run", {}))
    seed_match = re.search(r"(\d+)$", str(mainline.get("seed", "seed_0")))
    mainline_seed = int(seed_match.group(1)) if seed_match else 0
    mainline_fve = float(mainline.get("final_metrics", {}).get("logit_trig_fve_adaptive", 0.0))
    if mainline_fve <= 0 and corr_min.get("seeds"):
        seed_name = mainline.get("seed", "seed_0")
        for s in corr_min["seeds"]:
            if s.get("seed") == seed_name:
                mainline_fve = float(s.get("fve_adaptive", 0.0))
                break

    readout_above_90 = metrics.get("readout", {}).get("n_directions_above_90pct", 0)
    ptrm = metrics.get("ptrm_fve", {})
    ptrm_clean = int(ptrm.get("n_clean_ptrm", minimal_clean))
    ptrm_fve_mean = float(
        sum(s.get("fve_adaptive", 0) for s in ptrm.get("seeds", [])) / max(len(ptrm.get("seeds", [])), 1)
    ) if ptrm.get("seeds") else minimal_fve

    lines = [
        "% Auto-generated by write_paper_v2_metrics.py",
        f"\\newcommand{{\\VTwoNandaSeedsClean}}{{{nanda_clean}}}",
        f"\\newcommand{{\\VTwoNandaFVEAdaptive}}{{{_fmt(nanda_fve)}}}",
        f"\\newcommand{{\\VTwoMinimalSeedsCleanFinal}}{{{minimal_clean}}}",
        f"\\newcommand{{\\VTwoMinimalFVEAdaptiveFinal}}{{{_fmt(minimal_fve)}}}",
        f"\\newcommand{{\\VTwoMinimalFVEAdaptiveMean}}{{{_fmt(minimal_fve)}}}",
        f"\\newcommand{{\\VTwoMinimalSeedsCleanPTRM}}{{{ptrm_clean}}}",
        f"\\newcommand{{\\VTwoMinimalFVEAdaptivePTRM}}{{{_fmt(ptrm_fve_mean)}}}",
        f"\\newcommand{{\\VTwoMainlineSeed}}{{{mainline_seed}}}",
        f"\\newcommand{{\\VTwoMainlineFVE}}{{{_fmt(mainline_fve)}}}",
        f"\\newcommand{{\\VTwoReadoutDirsAboveNinetyPct}}{{{readout_above_90}}}",
        f"\\newcommand{{\\VTwoBMINSeeds}}{{{int(_ms(minimal, 'test_accuracy').get('n', 5))}}}",
        f"\\newcommand{{\\VTwoBestWeightDecay}}{{{metrics.get('best_weight_decay', 1.0)}}}",
        "",
    ]
    out.write_text("\n".join(lines))


def write_main_results(metrics: Dict[str, Any], out: Path, corrected: Dict[str, Any] | None = None) -> None:
    corrected = corrected or {}
    rows = []
    for name, label in [("nanda_a_mlp", "Nanda 1-layer"), ("trm_minimal", "TRM minimal")]:
        payload = metrics.get("models", {}).get(name, {})
        corr = corrected.get(name) or payload.get("corrected_fve", {})
        if not payload and not corr:
            continue
        seeds = payload.get("seeds", [])
        if seeds:
            acc_mean, acc_std = _mean_std(
                [s.get("history_metrics", {}).get("final", {}).get("test_accuracy", 0.0) for s in seeds]
            )
        else:
            # Corrected-FVE JSON present but no per-seed aggregate (e.g. nanda only on remote).
            acc_mean, acc_std = 1.0, 0.0
        corr_seeds = corr.get("seeds", [])
        if corr_seeds:
            fve_mean, fve_std = _mean_std([cs.get("fve_adaptive", 0.0) for cs in corr_seeds])
        else:
            fve_mean, fve_std = float(corr.get("mean_fve_adaptive", 0.0)), 0.0
        n_clean = int(corr.get("n_seeds_adaptive_ge_0.95", 0))
        n = int(corr.get("n_seeds", len(seeds)))
        rows.append(
            " & ".join([label, _fmt_pm(acc_mean, acc_std), _fmt_pm(fve_mean, fve_std), f"{n_clean}/{n}"])
            + r" \\"
        )
    table = "\n".join(
        [
            r"\begin{tabular}{lrrr}",
            r"\toprule",
            r"Model & Test acc & Adaptive FVE & Seeds $\geq 0.95$ \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )
    out.write_text(table)


def write_neuron_readout(readout: Dict[str, Any], out: Path) -> None:
    rows = readout.get("readout_rows", [])
    if not rows:
        out.write_text("% neuron readout pending\n")
        return
    lines = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Component & Freq $k$ & Neuron & Coef & FVE (\%) \\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            " & ".join(
                [
                    r["component"].replace("_", r"\_"),
                    str(r["frequency"]),
                    str(r["neuron_index"]),
                    f"{r['coefficient']:.2f}",
                    f"{r['fve']:.1f}",
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out.write_text("\n".join(lines))


def write_robustness_data_fraction(metrics: Dict[str, Any], out: Path) -> None:
    rows_data = metrics.get("ep3_data_fraction_sweep", [])
    if rows_data:
        from collections import defaultdict

        by_frac: dict[str, list] = defaultdict(list)
        for r in rows_data:
            by_frac[str(r.get("frac_train", ""))].append(r)
        lines = [
            r"\begin{tabular}{rrrrr}",
            r"\toprule",
            r"Frac train & Seeds $\geq 0.95$ & Grok step (mean) & Final FVE (mean) & Final acc (mean) \\",
            r"\midrule",
        ]
        for frac in sorted(by_frac.keys(), key=float):
            group = by_frac[frac]
            fves = [float(g.get("final_fve", 0)) for g in group]
            accs = [float(g.get("final_accuracy", 0)) for g in group]
            groks = [int(g.get("grokking_step", -1)) for g in group if int(g.get("grokking_step", -1)) >= 0]
            n_clean = sum(1 for f in fves if f >= 0.95)
            grok_mean = sum(groks) / max(len(groks), 1)
            lines.append(
                f"{frac} & {n_clean}/{len(group)} & {int(grok_mean)} & {_fmt(sum(fves)/max(len(fves),1))} & {_fmt(sum(accs)/max(len(accs),1))} \\\\"
            )
        lines.extend([r"\bottomrule", r"\end{tabular}", ""])
        out.write_text("\n".join(lines))
        return
    lines = [
        r"\begin{tabular}{rrrr}",
        r"\toprule",
        r"Frac train & Grok step & Final FVE & Final acc \\",
        r"\midrule",
    ]
    for r in rows_data:
        fm = r.get("final_metrics", {})
        lines.append(
            " & ".join(
                [
                    str(r.get("frac_train", "")),
                    str(int(r.get("grokking_step", -1))),
                    _fmt(float(r.get("final_fve", fm.get("logit_trig_fve_adaptive", 0)))),
                    _fmt(float(r.get("final_accuracy", fm.get("test_accuracy", 0)))),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out.write_text("\n".join(lines))


def write_robustness_weight_decay(metrics: Dict[str, Any], out: Path) -> None:
    ep3_rows = metrics.get("ep3_weight_decay_sweep", [])
    if ep3_rows:
        from collections import defaultdict

        by_wd: dict[str, list] = defaultdict(list)
        for r in ep3_rows:
            by_wd[str(r.get("weight_decay", r.get("tag", "")))].append(r)
        lines = [
            r"\begin{tabular}{rrrr}",
            r"\toprule",
            r"Weight decay $\lambda$ & Seeds & Mean final FVE & Mean final acc \\",
            r"\midrule",
        ]
        for wd in sorted(by_wd.keys(), key=float):
            group = by_wd[wd]
            fves = [float(g.get("final_fve", g.get("final_metrics", {}).get("logit_trig_fve_adaptive", 0))) for g in group]
            accs = [float(g.get("final_accuracy", g.get("final_metrics", {}).get("test_accuracy", 0))) for g in group]
            n_clean = sum(1 for f in fves if f >= 0.95)
            lines.append(
                f"{wd} & {n_clean}/{len(group)} & {_fmt(sum(fves)/max(len(fves),1))} & {_fmt(sum(accs)/max(len(accs),1))} \\\\"
            )
        lines.extend([r"\bottomrule", r"\end{tabular}", ""])
        out.write_text("\n".join(lines))
        return
    candidates = metrics.get("ep1_weight_decay_sweep", [])
    lines = [
        r"\begin{tabular}{rrr}",
        r"\toprule",
        r"Weight decay $\lambda$ & Seeds $\geq 0.95$ & Mean adaptive FVE \\",
        r"\midrule",
    ]
    for c in candidates:
        lines.append(
            " & ".join(
                [
                    str(c.get("weight_decay", "")),
                    f"{c.get('n_clean_final', 0)}/{c.get('n_seeds', 5)}",
                    _fmt(float(c.get("mean_fve_adaptive", 0))),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out.write_text("\n".join(lines))


def write_checkpoint_compare(metrics: Dict[str, Any], out: Path) -> None:
    minimal = metrics.get("models", {}).get("trm_minimal", {})
    rows = []
    for s in minimal.get("seeds", []):
        seed = s.get("seed", "")
        final = s.get("final_metrics", {})
        grok = s.get("history_metrics", {}).get("grokking", {})
        best = s.get("history_metrics", {}).get("best_fve", {})
        rows.append(
            " & ".join(
                [
                    seed.replace("_", r"\_"),
                    _fmt(float(final.get("logit_trig_fve_adaptive", 0))),
                    _fmt(float(grok.get("logit_trig_fve_adaptive", 0))),
                    _fmt(float(best.get("logit_trig_fve_adaptive", best.get("logit_trig_fve_faithful", 0)))),
                ]
            )
            + r" \\"
        )
    out.write_text(
        "\n".join(
            [
                r"\begin{tabular}{lrrr}",
                r"\toprule",
                r"Seed & Final FVE & Grokking FVE & Best-FVE FVE \\",
                r"\midrule",
                *rows,
                r"\bottomrule",
                r"\end{tabular}",
                "",
            ]
        )
    )


def write_neuron_readout_appendix(readout: Dict[str, Any], out: Path) -> None:
    rows = readout.get("readout_rows", [])
    if not rows:
        out.write_text("% neuron readout appendix pending\n")
        return
    lines = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Component & Freq $k$ & Neuron & Coef & Neuron FVE (\%) \\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            " & ".join(
                [
                    r["component"].replace("_", r"\_"),
                    str(r["frequency"]),
                    str(r["neuron_index"]),
                    f"{r['coefficient']:.2f}",
                    f"{r.get('neuron_fve', 0):.1f}",
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out.write_text("\n".join(lines))


def write_attention_heads(mainline_dir: str | None, out: Path) -> None:
    if not mainline_dir:
        out.write_text("% attention heads pending\n")
        return
    ht_path = Path(mainline_dir) / "analysis/head_trig/head_trig_fits.json"
    if not ht_path.exists():
        out.write_text("% attention heads pending\n")
        return
    rows = json.loads(ht_path.read_text()).get("rows", [])
    lines = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Layer & Head & Freq $k$ & Coef & FVE (\%) \\",
        r"\midrule",
    ]
    for r in rows:
        coef = r.get("coef_cos") if abs(r.get("coef_cos", 0)) >= abs(r.get("coef_sin", 0)) else r.get("coef_sin", 0)
        phase = r.get("phase", "a+b")
        target = r.get("target", "a")
        lines.append(
            f"L{r['layer']} & H{r['head']} & {r['dominant_frequency']} ({phase}, ${target}$) & "
            f"{coef:.2f} & {r['fve_pct']:.1f} \\\\"
        )
    if len(lines) == 4:
        lines.append(r"\multicolumn{5}{c}{\textit{No head trig fits available}} \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out.write_text("\n".join(lines))


def write_per_seed_readout_tables(results_root: Path, best_wd: float, tables: Path) -> None:
    model_root = results_root / "ep1" / f"wd_{best_wd}" / "trm_minimal"
    if not model_root.exists():
        model_root = results_root / "trm_minimal"
    for seed_dir in sorted(model_root.glob("seed_*")):
        ro_path = seed_dir / "analysis/readout/nanda_readout.json"
        if not ro_path.exists():
            continue
        readout = json.loads(ro_path.read_text())
        seed = seed_dir.name.replace("seed_", "")
        write_neuron_readout(readout, tables / f"neuron_readout_seed{seed}.tex")


def write_per_seed_table(metrics: Dict[str, Any], out: Path, corrected: Dict[str, Any] | None = None) -> None:
    corrected = corrected or {}
    minimal = metrics.get("models", {}).get("trm_minimal", {})
    corr = corrected.get("trm_minimal") or minimal.get("corrected_fve", {})
    corr_by_seed = {cs.get("seed"): cs for cs in corr.get("seeds", [])}
    rows = []
    for s in minimal.get("seeds", []):
        seed_name = s.get("seed", "")
        final = s.get("history_metrics", {}).get("final", {})
        grok = s.get("history_metrics", {}).get("grokking", {})
        best = s.get("history_metrics", {}).get("best_fve", {})
        diag = s.get("seed_diagnosis", {})
        fve_adaptive = float(corr_by_seed.get(seed_name, {}).get("fve_adaptive",
                            final.get("logit_trig_fve_adaptive", 0.0)))
        rows.append(
            " & ".join(
                [
                    seed_name.replace("_", r"\_"),
                    _fmt(float(final.get("test_accuracy", 0))),
                    _fmt(fve_adaptive),
                    str(int(grok.get("step", diag.get("grokking_step", -1)))),
                    _fmt(float(best.get("logit_trig_fve_faithful", 0))),
                    ",".join(d.replace("_", r"\_") for d in diag.get("likely_causes", [])),
                ]
            )
            + r" \\"
        )
    table = "\n".join(
        [
            r"\begin{tabular}{lrrrr p{3.5cm}}",
            r"\toprule",
            r"Seed & Final acc & Final FVE & Grok step & Best FVE & Diagnosis \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )
    out.write_text(table)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results-root", required=True)
    ap.add_argument("--metrics", required=True)
    ap.add_argument("--paper-dir", required=True)
    ap.add_argument("--best-wd", required=True, type=float)
    args = ap.parse_args()

    root = Path(args.results_root)
    metrics = json.loads(Path(args.metrics).read_text())
    paper = Path(args.paper_dir)
    tables = paper / "tables"
    tables.mkdir(parents=True, exist_ok=True)

    corrected = None
    for corr_path in (root / "aggregate" / "corrected_fve_summary.json", root / "corrected_fve_summary.json"):
        if corr_path.exists():
            corrected = json.loads(corr_path.read_text())
            break
    nanda_corr_path = root / "aggregate" / "corrected_fve_nanda.json"
    if nanda_corr_path.exists():
        nanda_corr = json.loads(nanda_corr_path.read_text())
        if corrected is None:
            corrected = {}
        corrected.update(nanda_corr)

    # Load readout from mainline run if present.
    mainline_dir = metrics.get("models", {}).get("trm_minimal", {}).get("mainline_seed_run", {}).get("run_dir")
    if mainline_dir:
        candidate = Path(mainline_dir)
        if not candidate.exists():
            rel = str(mainline_dir)
            for anchor in ("ep1/", "trm_minimal/"):
                if anchor in rel:
                    rel = rel[rel.index(anchor) :]
                    break
            candidate = root / rel
        if not candidate.exists():
            candidate = root / "ep1" / f"wd_{args.best_wd}" / "trm_minimal" / "seed_0"
        mainline_dir = str(candidate) if candidate.exists() else mainline_dir
    readout = {}
    if mainline_dir:
        ro_path = Path(mainline_dir) / "analysis/readout/nanda_readout.json"
        if ro_path.exists():
            readout = json.loads(ro_path.read_text())
    above90 = sum(1 for r in readout.get("readout_rows", []) if r.get("fve", 0) >= 90)
    metrics["readout"] = {**readout, "n_directions_above_90pct": above90}

    write_metrics_v2(metrics, paper / "metrics_v2.tex", corrected)
    write_main_results(metrics, tables / "main_results.tex", corrected)
    write_neuron_readout(readout, tables / "neuron_readout.tex")
    write_neuron_readout_appendix(readout, tables / "neuron_readout_appendix.tex")
    write_robustness_data_fraction(metrics, tables / "robustness_data_fraction.tex")
    write_robustness_weight_decay(metrics, tables / "robustness_weight_decay.tex")
    write_per_seed_table(metrics, tables / "per_seed_metrics.tex", corrected)
    write_checkpoint_compare(metrics, tables / "checkpoint_compare.tex")
    write_attention_heads(mainline_dir, tables / "attention_heads.tex")
    write_per_seed_readout_tables(root, args.best_wd, tables)
    print(f"wrote paper v2 metrics to {paper}")


if __name__ == "__main__":
    main()
