#!/usr/bin/env python3
"""Write LaTeX metrics and tables for the hybrid latent grokking paper."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List


def _fmt(x: float) -> str:
    return f"{x:.3f}"


def _fmt_pm(mean: float, std: float) -> str:
    return f"{_fmt(mean)} $\\pm$ {_fmt(std)}"


def _ms(payload: Dict[str, Any], metric: str, prefix: str = "") -> Dict[str, float | int]:
    key = f"{prefix}{metric}" if prefix else metric
    return payload.get(key, payload.get(metric, {"mean": 0.0, "std": 0.0, "n": 0}))


def _corrected_macros(models: Dict[str, Any], corrected: Dict[str, Any] | None) -> List[str]:
    """Adaptive (data-driven key-frequency) FVE macros; fall back to legacy K=5
    means when the corrected summary is unavailable so the paper still compiles."""

    def legacy_mean(model: str) -> float:
        return float(_ms(models.get(model, {}), "logit_trig_fve_faithful", "final_").get("mean", 0.0))

    def block(model: str, key: str) -> Dict[str, Any]:
        return (corrected or {}).get(key, {})

    nanda = block("nanda_a_mlp", "nanda_a_mlp")
    minimal = block("trm_minimal", "trm_minimal")
    full = block("trm_full_b", "trm_full_b")
    nanda_mean = float(nanda.get("mean_fve_adaptive", legacy_mean("nanda_a_mlp")))
    minimal_mean = float(minimal.get("mean_fve_adaptive", legacy_mean("trm_minimal")))
    full_mean = float(full.get("mean_fve_adaptive", legacy_mean("trm_full_b")))
    nanda_clean = int(nanda.get("n_seeds_adaptive_ge_0.95", 0))
    minimal_clean = int(minimal.get("n_seeds_adaptive_ge_0.95", 0))
    ks = [int(s.get("n_key_freqs_adaptive", 0)) for s in nanda.get("seeds", [])]
    k_range = f"{min(ks)}--{max(ks)}" if ks else "5--9"
    return [
        "% Corrected adaptive-frequency FVE (analysis/corrected_fve_summary.py)",
        f"\\newcommand{{\\HybridNandaFVEAdaptive}}{{{_fmt(nanda_mean)}}}",
        f"\\newcommand{{\\HybridMinimalFVEAdaptive}}{{{_fmt(minimal_mean)}}}",
        f"\\newcommand{{\\HybridFullFVEAdaptive}}{{{_fmt(full_mean)}}}",
        f"\\newcommand{{\\HybridNandaSeedsClean}}{{{nanda_clean}}}",
        f"\\newcommand{{\\HybridMinimalSeedsClean}}{{{minimal_clean}}}",
        f"\\newcommand{{\\NandaAdaptiveKRange}}{{{k_range}}}",
    ]


def write_metrics(metrics: Dict[str, Any], out: Path, corrected: Dict[str, Any] | None = None) -> None:
    models = metrics.get("models", {})

    def val(model: str, metric: str, prefix: str = "final_") -> float:
        return float(_ms(models.get(model, {}), metric, prefix).get("mean", 0.0))

    def val_best(model: str, metric: str) -> float:
        return float(_ms(models.get(model, {}), metric, "best_fve_").get("mean", 0.0))

    n_total = max((int(_ms(models.get(m, {}), "test_accuracy").get("n", 0)) for m in models), default=0)

    best_min = models.get("trm_minimal", {}).get("best_seed_run", {})
    best_fve = best_min.get("best_fve", {})

    text = "\n".join(
        [
            "% Auto-generated by write_hybrid_paper_metrics.py",
            f"\\newcommand{{\\HybridNandaAcc}}{{{_fmt(val('nanda_a_mlp', 'test_accuracy'))}}}",
            f"\\newcommand{{\\HybridMinimalAcc}}{{{_fmt(val('trm_minimal', 'test_accuracy'))}}}",
            f"\\newcommand{{\\HybridFullAcc}}{{{_fmt(val('trm_full_b', 'test_accuracy'))}}}",
            f"\\newcommand{{\\HybridNandaFVE}}{{{_fmt(val('nanda_a_mlp', 'logit_trig_fve_faithful'))}}}",
            f"\\newcommand{{\\HybridMinimalFVE}}{{{_fmt(val('trm_minimal', 'logit_trig_fve_faithful'))}}}",
            f"\\newcommand{{\\HybridFullFVE}}{{{_fmt(val('trm_full_b', 'logit_trig_fve_faithful'))}}}",
            f"\\newcommand{{\\HybridMinimalFVEBest}}{{{_fmt(val_best('trm_minimal', 'logit_trig_fve_faithful'))}}}",
            f"\\newcommand{{\\HybridMinimalFVESeedZero}}{{{_fmt(float(best_fve.get('logit_trig_fve_faithful', val_best('trm_minimal', 'logit_trig_fve_faithful'))))}}}",
            f"\\newcommand{{\\BMINSeeds}}{{{n_total}}}",
            f"\\newcommand{{\\BMITestAcc}}{{{_fmt(val('trm_minimal', 'test_accuracy'))}}}",
            f"\\newcommand{{\\BMIFVEMean}}{{{_fmt(val_best('trm_minimal', 'logit_trig_fve_faithful'))}}}",
            f"\\newcommand{{\\BMITrigTestCE}}{{{_fmt(val('trm_minimal', 'trig_loss_test'))}}}",
            f"\\newcommand{{\\BMIFullTestCE}}{{{_fmt(val('trm_minimal', 'trig_loss_test'))}}}",
            f"\\newcommand{{\\BMIExcludedTestCE}}{{{_fmt(val('trm_minimal', 'excluded_loss_test'))}}}",
            "",
        ]
    )
    kf = best_min.get("best_fve", {}).get("key_frequencies", [])
    if kf:
        text += f"\\newcommand{{\\BMIKeyFreqs}}{{{','.join(str(int(k)) for k in kf)}}}\n"
        text += f"\\newcommand{{\\BMIWLKeyFreqs}}{{{','.join(str(int(k)) for k in kf)}}}\n"
    text += "\\newcommand{\\BMIEmGini}{0.000}\n"
    text += "\n".join(_corrected_macros(models, corrected)) + "\n"
    out.write_text(text)


def write_main_table(metrics: Dict[str, Any], out: Path) -> None:
    rows = []
    for name, payload in metrics.get("models", {}).items():
        acc = _ms(payload, "test_accuracy", "final_")
        fve = _ms(payload, "logit_trig_fve_faithful", "final_")
        trig = _ms(payload, "trig_loss_test", "final_")
        excl = _ms(payload, "excluded_loss_test", "final_")
        rows.append(
            " & ".join(
                [
                    name.replace("_", "\\_"),
                    _fmt_pm(float(acc["mean"]), float(acc["std"])),
                    _fmt_pm(float(fve["mean"]), float(fve["std"])),
                    _fmt_pm(float(trig["mean"]), float(trig["std"])),
                    _fmt_pm(float(excl["mean"]), float(excl["std"])),
                ]
            )
            + r" \\"
        )
    table = "\n".join(
        [
            r"\begin{tabular}{lrrrr}",
            r"\toprule",
            r"Model & Test Acc. & Faithful FVE & Trig CE & Excluded CE \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )
    out.write_text(table)


def write_checkpoint_table(metrics: Dict[str, Any], out: Path) -> None:
    """Final vs grokking vs best-FVE checkpoint comparison."""
    rows: List[str] = []
    for name, payload in metrics.get("models", {}).items():
        for ckpt_label, prefix in [
            ("Final", "final_"),
            ("Grokking", "grokking_"),
            ("Best FVE", "best_fve_"),
        ]:
            acc = _ms(payload, "test_accuracy", prefix)
            fve = _ms(payload, "logit_trig_fve_faithful", prefix)
            rows.append(
                " & ".join(
                    [
                        name.replace("_", "\\_"),
                        ckpt_label,
                        _fmt_pm(float(acc["mean"]), float(acc["std"])),
                        _fmt_pm(float(fve["mean"]), float(fve["std"])),
                    ]
                )
                + r" \\"
            )
    table = "\n".join(
        [
            r"\begin{tabular}{llrr}",
            r"\toprule",
            r"Model & Checkpoint & Test Acc. & Faithful FVE \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )
    out.write_text(table)


def _breakable(s: str) -> str:
    """Escape underscores and add line-break opportunities so long comma-joined
    cause strings wrap inside narrow p{} table columns instead of overflowing."""
    return s.replace("_", r"\_\allowbreak ").replace(",", r",\allowbreak ")


def write_per_seed_table(metrics: Dict[str, Any], out: Path) -> None:
    rows = []
    for model_name, payload in metrics.get("models", {}).items():
        for s in payload.get("seeds", []):
            seed = s.get("seed", "?").replace("seed_", "")
            fin = s.get("final_metrics", {})
            grok = s.get("history_metrics", {}).get("grokking", {})
            best = s.get("history_metrics", {}).get("best_fve", {})
            diag = s.get("seed_diagnosis", {})
            causes = ",".join(diag.get("likely_causes", []))
            rows.append(
                " & ".join(
                    [
                        model_name.replace("_", "\\_"),
                        seed,
                        _fmt(float(fin.get("test_accuracy", 0))),
                        _fmt(float(fin.get("logit_trig_fve_faithful", 0))),
                        str(int(grok.get("step", -1))),
                        _fmt(float(grok.get("logit_trig_fve_faithful", 0))),
                        str(int(best.get("step", -1))),
                        _fmt(float(best.get("logit_trig_fve_faithful", 0))),
                        _breakable(causes),
                    ]
                )
                + r" \\"
            )
    header = r"Model & Seed & Final Acc & Final FVE & Grok Step & Grok FVE & Best Step & Best FVE & Diagnosis \\"
    table = "\n".join(
        [
            r"\footnotesize",
            r"\setlength{\tabcolsep}{4pt}",
            r"\begin{longtable}{llrrrrrr p{2.4cm}}",
            r"\caption{Per-seed metrics and diagnosis (auto-generated).}\label{tab:perseed} \\",
            r"\toprule",
            header,
            r"\midrule",
            r"\endfirsthead",
            r"\multicolumn{9}{c}{\tablename\ \thetable\ -- continued} \\",
            r"\toprule",
            header,
            r"\midrule",
            r"\endhead",
            *rows,
            r"\bottomrule",
            r"\end{longtable}",
            r"\normalsize",
            "",
        ]
    )
    out.write_text(table)


def write_seed_variance_table(metrics: Dict[str, Any], out: Path) -> None:
    payload = metrics.get("models", {}).get("trm_minimal", {})
    rows = []
    for d in payload.get("seed_diagnoses", []):
        rows.append(
            " & ".join(
                [
                    str(d.get("grokking_step", -1)),
                    _fmt(float(d.get("peak_fve", 0))),
                    str(d.get("peak_fve_step", -1)),
                    _fmt(float(d.get("final_fve", 0))),
                    _fmt(float(d.get("fve_drop_after_peak", 0))),
                    _breakable(",".join(d.get("likely_causes", []))),
                ]
            )
            + r" \\"
        )
    table = "\n".join(
        [
            r"\begin{adjustbox}{max width=\linewidth}",
            r"\begin{tabular}{rrrrr p{4cm}}",
            r"\toprule",
            r"Grok Step & Peak FVE & Peak Step & Final FVE & FVE Drop & Cause \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{adjustbox}",
            "",
        ]
    )
    out.write_text(table)


def write_corrected_fve_table(corrected: Dict[str, Any], out: Path) -> None:
    """Legacy K=5 vs data-driven adaptive FVE (from corrected_fve_summary.py)."""
    labels = {
        "nanda_a_mlp": "Nanda 1-layer",
        "trm_minimal": "TRM minimal",
        "trm_full_b": "TRM full (ACT)",
    }
    rows: List[str] = []
    for key, label in labels.items():
        block = corrected.get(key, {})
        if not block:
            continue
        ks = [int(s.get("n_key_freqs_adaptive", 0)) for s in block.get("seeds", [])]
        krange = f"{min(ks)}--{max(ks)}" if ks else "--"
        n95 = block.get("n_seeds_adaptive_ge_0.95", 0)
        n = block.get("n_seeds", 0)
        rows.append(
            " & ".join(
                [
                    label,
                    _fmt(float(block.get("mean_fve_legacy_k5", 0.0))),
                    _fmt(float(block.get("mean_fve_adaptive", 0.0))),
                    f"{n95}/{n}",
                    krange,
                ]
            )
            + r" \\"
        )
    table = "\n".join(
        [
            r"\begin{tabular}{lrrrr}",
            r"\toprule",
            r"Model & Legacy FVE (K=5) & Adaptive FVE & Seeds $\geq 0.95$ & $K$ range \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )
    out.write_text(table)


def write_appendix_checkpoint_trajectory(results_root: Path, out: Path, *, model: str, seed: str) -> None:
    hist_path = results_root / model / seed / "training_history.json"
    if not hist_path.exists():
        out.write_text("% trajectory table not found\n")
        return
    history = json.loads(hist_path.read_text())
    rows = sorted([r for r in history if str(r.get("step", "")).isdigit()], key=lambda r: int(r["step"]))
    # Condense: keep first, last, and an even sample in between (<= 12 rows).
    if len(rows) > 12:
        idx = sorted({0, len(rows) - 1, *[round(i * (len(rows) - 1) / 11) for i in range(12)]})
        rows = [rows[i] for i in idx]
    lines = [
        f"% Per-checkpoint metrics: {model} {seed}",
        r"\begin{longtable}{rrrrrrr}",
        r"\toprule",
        r"Step & Test Acc & Trig CE & Excl CE & Emb Gini & FVE & Test Loss \\",
        r"\midrule",
        r"\endhead",
    ]
    for r in rows:
        fve = r.get("logit_trig_fve_faithful", 0)
        if isinstance(fve, dict):
            fve = fve.get("fve_mean", 0)
        lines.append(
            " & ".join(
                [
                    str(int(r["step"])),
                    _fmt(float(r.get("test_acc", 0))),
                    _fmt(float(r.get("trig_loss_test", 0))),
                    _fmt(float(r.get("excluded_loss_test", 0))),
                    _fmt(float(r.get("embedding_gini", 0))),
                    _fmt(float(fve)),
                    _fmt(float(r.get("test_loss", 0))),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}", ""])
    out.write_text("\n".join(lines))


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--metrics", required=True)
    p.add_argument("--results-root", default="")
    p.add_argument("--paper-dir", default="pluto/trm/base_mechanistic_interpretability/paper")
    args = p.parse_args()
    metrics = json.loads(Path(args.metrics).read_text())
    paper = Path(args.paper_dir)
    tables = paper / "tables"
    tables.mkdir(parents=True, exist_ok=True)
    corrected = None
    results_root_str = args.results_root or metrics.get("results_root", "")
    if results_root_str:
        root = Path(results_root_str)
        for corr_path in (root / "corrected_fve_summary.json", root / "aggregate" / "corrected_fve_summary.json"):
            if corr_path.exists():
                corrected = json.loads(corr_path.read_text())
                break
    write_metrics(metrics, paper / "metrics_hybrid.tex", corrected)
    write_main_table(metrics, tables / "main_results.tex")
    write_checkpoint_table(metrics, tables / "checkpoint_comparison.tex")
    write_per_seed_table(metrics, tables / "per_seed_metrics.tex")
    write_seed_variance_table(metrics, tables / "trm_minimal_seed_variance.tex")
    if corrected:
        write_corrected_fve_table(corrected, tables / "corrected_fve.tex")
    results_root = Path(args.results_root) if args.results_root else Path(metrics.get("results_root", "."))
    for model in ["nanda_a_mlp", "trm_minimal", "trm_full_b", "trm_full_a"]:
        traj_out = tables / f"trajectory_{model}_seed0.tex"
        hist_path = results_root / model / "seed_0" / "training_history.json"
        if hist_path.exists():
            write_appendix_checkpoint_trajectory(results_root, traj_out, model=model, seed="seed_0")
        else:
            print(f"skip trajectory {model}: no {hist_path}")
    print(f"wrote hybrid paper metrics to {paper}")


if __name__ == "__main__":
    main()
